# Debian Slim 기반 경량 이미지
FROM debian:bookworm-slim

ENV TELEPORT_VERSION=17.7.1

# 필수 패키지 설치
RUN apt-get update && apt-get install -y \
    nginx \
    supervisor \
    curl \
    ca-certificates \
    procps \
    && rm -rf /var/lib/apt/lists/*

RUN curl https://cdn.teleport.dev/install.sh | bash -s ${TELEPORT_VERSION} oss

# 디렉토리 생성
RUN mkdir -p /var/lib/teleport \
    /etc/teleport \
    /var/log/supervisor \
    /var/log/nginx \
    /var/log/teleport \
    /run/nginx

# Nginx 기본 설정 제거
RUN rm -f /etc/nginx/sites-enabled/default

# Teleport 바이너리 복사

# 포트 노출
EXPOSE 80 3022 3080

# Supervisor 실행
CMD ["/usr/bin/supervisord", "-n", "-c", "/etc/supervisor/conf.d/supervisord.conf"]
